### ISSUE TITLE
Add a third column to the homepage

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#116]
The bottom of the homepage has two columns, "Featured Users" and "Featured Groups" -- and room for a third column, but nothing there.

Something about Group Projects and/or Solo Actions would make a lot of sense there.

(Relatedly, but should really be in a separate ticket: we have no Featured Anythings right now.  Maybe the queries should be changed to talk about Most Recently Created/Modified/Acted Upon instead.  I think Jon L already filed some tickets talking about this but I'll look them up later.)

**Comment by jwarnow** [comment]
I like Featured Projects, Recent Activity, and Featured Groups

**Comment by ejucovy** [comment]
began to stub this out in 9b0b0b5
