### ISSUE TITLE
Replace site blog with a link to 350.org blog

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#119]
The site blog feature seems redundant with 350.org's own blog that posts updates to the main page at http://350.org

I think it would make sense to just link out directly to that blog for now, instead of having a separate blog for site managers at groups.350.org/blog

But, is there a URL that goes directly to the 350.org blog?  The 350.org homepage seems to stream blog posts, but they're a bit buried under the top section.

**Comment by jwarnow** [comment]
Good call -- you can use this: http://www.350.org/about/blog

**Comment by ejucovy** [comment]
0908e822181b2f412e2333dff10eb5aafe43ddbd and ea83e985b3fe75787ecd662a5798775fd555f9f9

**Comment by ejucovy** [comment]
Whoops, also 1c21456 wraps up the missing pieces that I neglected to commit along with ea83e98 -- wiring up the redirection from all /blog/ URLs to the 350 blog.
