### ISSUE TITLE
Enable Social Network buttons/links for groups

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#123]
Couldn't find this in another ticket, so submitting a new one here -- feel free to close if redundant. 

Groups should have the option to link out to their Facebook and Twitter accounts, and if they do it should pull in big buttons/links on their Group Homepage like "Connect with this group on Facebook" "Follow this group on Twitter"

**Comment by ejucovy** [comment]
https://github.com/350org/localpower/compare/faa91d7c97...a7da3acd0f

Probably a few loose ends to polish up, so just let me know what you think.

**Comment by ejucovy** [comment]
There's a sample at http://groups.350.org/long-island/ (or you can try it with a group you're a manager of)

**Comment by jwarnow** [comment]
Nice! What do you think about buttonifying them? Also, I'm seeing the top section of that group in a frame with a horizontal scroll bar on the bottom. Is that normal?

## 

Jon Warnow
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ejucovy** [comment]
What do you mean by buttonifying them?

**Comment by jwarnow** [comment]
Ha! I see you don't share my tendency to verbify nouns. ;)

I mean use pretty buttons instead of links for "Find Us on
Facebook/Twitter":
http://www.ourgemcodes.com/wp-content/uploads/2011/06/facebook.png

No biggie, but could be nice.

Seems that group pages are throwing Django errors now though?
