### ISSUE TITLE
Auto-add group membership when signing a petition

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#136]
> So when a petition is associated with a group, do signatories to that petition get auto-added to that group?

Notes:
- Of course, we can only do this when the user is logged in.  (We allow anonymous signatures.)
- We should probably have an opt-out checkbox per group, which would default to opt-in.

**Comment by ejucovy** [comment]
Should we default the checkbox to opt-out (unchecked) for closed groups?  If a closed group wants to circulate a petition, it might get annoying having to moderate automatically initiated group-join requests for each petition signature.

**Comment by jwarnow** [comment]
Hrm -- well, short of requiring users to create an account and/or log in, is
there any other way we can add petition signatories to an email list that
the local group admins can email?

**Comment by ejucovy** [comment]
> Hrm -- well, short of requiring users to create an account and/or log in, is
> there any other way we can add petition signatories to an email list that
> the local group admins can email?

Yeah.  This will involve a few separate features though.  I'll break it down in a subsequent comment.

Note, though: I believe there's currently no way for group admins to email all their members through the site.  So, even for the simple cases (open group, logged-in user signing the petition) adding signatories to a linked group doesn't actually address this user story.

**Comment by ejucovy** [comment]
1. Add a "email all people who have signed this petition" feature -- this means adding a new database model and a new message stream, as well as the UI for it.
2. Make that feature available only to the petition's creator.
3. If the petition is linked with one or more groups, make the feature available also to the administrators of the linked group(s)

Implementation notes:
- These emails would not be reply-able.
- Should the reply-to address be set to the email address of the admin who initiated the message?
- Adding a "browse message archive" UI would be additional work, but we could add that on later.

**Comment by ejucovy** [comment]
The implementation should expect subsequent addition of similar features for "group admins: message all users in this group" and "event creators and linked group admins: message all RSVPs to this event."

**Comment by jwarnow** [comment]
Thinking through this feature has revealed some missing pieces that will
require more work -- but that are pretty crucial I think.

As for your questions:
- Should the reply-to address be set to the email address of the admin who
  initiated the message?

YES, I think so.
- Adding a "browse message archive" UI would be additional work, but we
  could add that on later.
  YES, but later.

*there's currently no way for group admins to email all their members
through the site.
YIKES. This seems like a top-priority feature to implement. Can't believe I
didn't realize this was missing.

-jw-

**Comment by ejucovy** [comment]
> > *there's currently no way for group admins to email all their members through the site.
> > YIKES. This seems like a top-priority feature to implement. Can't believe I didn't realize this was missing.

So, as discussed over email, I realized this is wrong: creating a new Group Discussion == emailing all of the group's members.

Given that -- would you prefer to have petition signatories and event RSVPs added to the linked group(s), or having a feature that lets event/campaign admins (including their linked-group admins) send a message to the participants?  Or both?

**Comment by jwarnow** [comment]
Both, if it's not too hard.

**Comment by ejucovy** [comment]
OK.  Tracking the "send a message to petition/event participants" feature in #139.

**Comment by jwarnow** [comment]
I just realized, getting added to the group should probably be opt-out check box. 

So, for petitions that are associated with a  group, we should add a pre-ticked checkbox to the form. Something like:

"YES, add me to [[GROUP NAME]] and keep me posted on local activities."

Doable?

**Comment by ejucovy** [comment]
Stubbing out necessary HTML in 988ce0b

**Comment by ejucovy** [comment]
Implemented in d4b71677385ffe1a7a1491f38535a1300a2876b6 and a2b2e2e
