### ISSUE TITLE
Allow admins to email event participants, petition signatories

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#139]
We want to allow admins to email event participants.  Admins are:
- The event's creator
- All administrators of all groups linked to the event, if any
- All event hosts?

Similarly, for campaigns, we want to allow admins to email all petition signatories.  Admins in this context are:
- The petition's creator
- All administrators of all groups linked to the campaign, if any

For some simplifying constraints, we can assume for now that:
- the email's reply-to will be set to the message's initiator (not a magic reply-to address posting responses to the site)
- the message will not be viewable in an archive at first

**Comment by ejucovy** [comment]
So, seems like we can/should unify this with group discussions somehow.  Very rough (and incomplete) implementation sketch, thinking out loud:
- Add some kind of "targets" field on `group.Discussion` which can be set to one of:
  *\* the group itself
  *\* any event associated with the group
  *\* any campaign associated with the group
- This field would be used to determine both the recipients of the Discussion's associated `messaging.Message` objects, and also their `Reply-to` values.
- We'd filter the group_disc_list and group_disc_detail views to exclude any Discussion with `target != {{the group itself}}`
- Add some UI(s) for selecting a new discussion's `target`?
- What about recipients who aren't site members?  Do we need to plan ahead for handling email replies in that case?  Possibly.

**Comment by ejucovy** [comment]
Would this approach break down for an event/campaign which is linked to multiple groups?  Would we be better off generalizing the `group.Discussions` code to be altogether agnostic of whether it's attached to a group/event/campaign?

**Comment by ejucovy** [comment]
What about the emails that get sent out?  Right now I'm giving them a subject line of `[groupname] message - 350 Groups` -- should it be [eventname] instead for an event-attached message?

**Comment by ejucovy** [comment]
So actually I think three independent fields on Discussion:

1) "show in archives?"
2) "allow replies?"
3) target

For now, (2) will only control whether a message gets a magic Reply-To header, so in the UI I'll call it "allow replies by email."  For now, a message can be made a "non-replyable announcement" by setting both (1) and (2) to false.  Later, we'll want a way to show non-replyable announcements in the archive, so we can extend the domain of setting (2) to control replyability through the web as well as by email, but I think that's unnecessary extra work for the first stage.

(1) actually already exists as the `is_public` flag, but that flag isn't working right -- the discussion-list and discussion-detail views both forget to check for it.  So fixing that is step 1.

**Comment by ejucovy** [comment]
Filed new issues #140 and #141 to track "show in archives?" and "allow replies?" features.

**Comment by ejucovy** [comment]
> Would this approach break down for an event/campaign which is linked to multiple groups? Would we be better off generalizing the group.Discussions code to be altogether agnostic of whether it's attached to a group/event/campaign?

Also would this approach break down for an even/tcampaign which is not linked to any groups?

**Comment by ejucovy** [comment]
Well, I'm trying it out, on the theory that we can design for the common case being one and only group per event/petition.  Backend work done in 3f00c94

**Comment by jwarnow** [comment]
Confirming: event hosts are event admins.

**Comment by ejucovy** [comment]
Implementation for events: https://github.com/350org/localpower/compare/e793c6e162c6e2d72df78216d49124c2cddb8677%5E...ba94437b

and bugfix: 8548614

**Comment by ejucovy** [comment]
Implementation for campaigns: a61e77a

and bugfix: 8548614

**Comment by ejucovy** [comment]
The reuse of groups.Discussion was problematic and felt brittle, because (among other reasons) it only works when there is a related group and the person who is trying to send a message is a manager of a related group.  So I just defined a new discussions.Discussion model -- still reusing the same messages and forms -- which uses a generic foreign key rather than hardcoding a group attachment.  Eventually the group discussions ought to be refactored to use this implementation as well, but it's sufficient as it is for now.

That was done in 0608058ba3954878187498ccf9a1a40c24c1d06e.
