### ISSUE TITLE
Merge Facebook "Discussions" tabs into Overview

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#142]
CAMPAIGNS
- Move Facebook comments under the form in Overview. Remove Discussions.

EVENTS
- Move “discussions” (Facebook comments) to below “overview” - just seems like one less thing to click.

**Comment by ejucovy** [comment]
Implemented for Campaigns and Events in f42a3a5.

**Comment by ejucovy** [comment]
Kelly/Alex: what about for Projects?  (Group and/or solo.)  Those also have a Facebook-comments "Discussions" tab.  But merging it with the main content tab seems less right in that case, since the content of a Project feels kinda heavier than the Event/Campaign "overview" tab.

**Comment by abea** [comment]
I think leaving it separate on projects is fine.

**Comment by kmblynn** [comment]
Agreed!
