### ISSUE TITLE
Put content in homepage "four metrics" block

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#146]
Four metrics blocks - seems like a lot of real estate to devote to a few numbers.  Would like to highlight metrics, but maybe just in one of those boxes?  Ideas for 4 boxes:
- Highlight a few metrics to start in one box: Number of 350 groups, Number of countries (represented by members and groups)
- Start here (sort of post it note style): 1) Learn about 350 groups [about page] 2) Search for groups near you  3) Sign up to get started (register as an organizer)
- 350 Resources (link to our guides, materials, whether hosted here or on 350.org)
- Workshops

**Comment by kmblynn** [comment]
Would like to change this:

Start here (sort of post it note style): 1) Learn about 350 groups [about page] 2) Search for groups near you 3) Sign up to get started (register as an organizer), to:

Get started: 1) Learn about 350 Local (about page)
2) Sign up (member registration)
3) Search for groups near you (map)

Also, Ethan, do you need graphics from us or anything else to make these changes?

**Comment by ejucovy** [comment]
Actually, if you could send me a mockup of how this should look, that would be very helpful -- I'm not sure I understand how you want to fit all this in the boxes.

Also, what should the "Resources" and "Workshops" link to?

**Comment by kmblynn** [comment]
Hey Ethan - I made a mockup that is too small and might not serve your
purpose - let me know if this is helpful enough.  Basically we want the
feature blocks to look like the homepage feature blocks of 350.org, more or
less.

First block: counters - in the past we've had this look like a little
table, which looks sort of nice, if that's possible.

For the other blocks, do you want me to get graphics to you from our
graphic designer?

Cheers,

Kelly

350.org  |  skype: kmblynn | cell: +1 610 220-5378 | twitter: kellyblynn

On Thu, Nov 24, 2011 at 4:51 PM, ejucovy <
reply@reply.github.com

**Comment by kmblynn** [comment]
Hey Ethan,

Alex and I met today and made a small change here - sorry about that, but its pretty simple.  In the second feature box, we'd like to feature the "About" page, is all.  So it's:

1st block: Counters
2nd block: Link to about page.  Text in a box, "Learn more about 350 Local".
3rd block:  Organizer resources - www.350.org/resources
4th block: Workshops - workshops.350.org

Thanks!

**Comment by abea** [comment]
Please update

**Comment by ejucovy** [comment]
I never received the mockup for this -- could you send it to my email directly?

**Comment by ejucovy** [comment]
I've received the changes from Matthew and pushed them live in 83f04a4ae475da97f9cc8be6bd25b42321bdb34d
