### ISSUE TITLE
Fill in content for three columns on homepage

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#149]
Suggestions for three columns at the bottom:
- Community blog snippets (if ready in time) (get rid of featured projects)
  *\* Blog only for groups and without moderation.
- Featured 350 groups (again, change icon to 350 logo)
- New members (instead of users terminology, as desc. above)
  *\* Button: “Find members”
  *\* Just use first name, last initial

**Comment by ejucovy** [comment]
> Community blog snippets (if ready in time) (get rid of featured projects) *\* Blog only for groups and without moderation.

Since we agreed to defer the blog feature, what should I put in the first column instead?

**Comment by kmblynn** [comment]
I think "Find events near you" would make sense.

**Comment by ejucovy** [comment]
bc037030, e1a32829, 9daf231

**Comment by ejucovy** [comment]
Replaced the projects column with an events column in 8d5615c.
