### ISSUE TITLE
Flat page width

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#155]
I created a flat page for the group submission form at http://local.350.org/groups/form/. For some reason, the content seems limited to about 2/3rds of the page. It will need to be full width to properly display the form. The form styling itself isn't setting a width. Let me know if we need to fix this styling on our end or if you can.

**Comment by ejucovy** [comment]
Fixed in eeed36c9e1cfa9f0e32e4a9c2e41e053cd8aba4e
