### ISSUE TITLE
Separate group items

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#159]
At http://local.350.org/350-dc/#discussions, for example, the sections as you scroll down run into one another. Would you ad some kind of divider? I was thinking just a horizontal line, but I'm open to other thoughts as well.

**Comment by abea** [comment]
I just realized this may be a problem with the tabs not working. If so, that is something to be fixed. The styling changes might have done that.

**Comment by ejucovy** [comment]
Hmm, the tabs are (still) working for me -- what browser and browser version are you using?  And could you send me a screenshot?

**Comment by ejucovy** [comment]
I haven't been able to reproduce this on any browser/OS combination I've tried.  I think there's probably some cached CSS somewhere that's interfering.  Could you try clearing out your browser's cache and saved history and see if that helps?

**Comment by abea** [comment]
I cleared my cache, cookies, etc and am still getting this problem on my
group and user pages in Chrome. In Firefox it looks fine.

Alex Bea
(202) 525-6703 | http://350.org

On Mon, Dec 26, 2011 at 1:01 PM, ejucovy <
reply@reply.github.com

**Comment by abea** [comment]
I found the problem here. I went through my browser extensions one by one and the problem disappeared when I removed the Facebook Disconnect app - https://chrome.google.com/webstore/detail/ejpepffjfmamnambagiibghpglaidiec

I'll probably continue to use the app, but disable it when I need the proper view on 350 Local. Sorry for the trouble.

**Comment by ejucovy** [comment]
Ah!  That's great to hear.  I kept forgetting to ask you about extensions. :-/  

I'll see if I can track down the reason for the incompatibility.
