### ISSUE TITLE
Update slider

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#160]
Content as follows:
1. Title: Join 350 Local
   Text: Organize to fight climate change where you live!
   From Afghanistan to Zimbabwe, people in nearly every country on the planet are mobilizing their communities for just solutions to the climate crisis. 350 Local is designed to make it simple to connect with other climate activists where we live, build powerful local movements to transform our communities, and stand in solidarity with one another globally to stop climate change.  Let’s build this movement together!
   Button: Create an account
   Image: Vietnam bicycle photo pile (currently on "Start Local Projects")
2. Title: Find a group near you.
   Text: Search the map to see if there’s a group near you
   Get involved with a local group to build local power. With 350 Local, you can connect with local activists to take on projects, launch campaigns, and more.
   Button: Search the map
   Image: Magnifying glass over 350 person (currently on "Welcome")
3. Title: Start organizing!
   Text: Start a project to build your local movement
   There's plenty we can all do at the local level to fight climate change, build a movement, and transform our communities from the ground up. Check out the projects on this website for ideas to build your team, educate your community, and advocate for solutions in your community.
   Button: See all projects
   Image: 3 men in light blue shirts (currently on "find local groups")

**Comment by abea** [comment]
Ethan - I see I can edit the text in Transifex, but I don't know about the photos or number of slides. Let me know if I'm able to do those or if you need to.

**Comment by ejucovy** [comment]
The number of slides can't be changed at the moment -- the javascript is hardcoded to expect four slides unfortunately.

The photos (like any images on the site) can be changed using the asset manager in the Admin site: http://local.350.org/admin/assetmanager/siteasset/
