### ISSUE TITLE
Give control over project icons

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#164]
We need to have control over the icons for projects. I tried using existing projects as much as possible, but the images broke once the slug changed from renaming the page (e.g., http://local.350.org/projects/energy-efficiency/). There was a house with an A+ for that one, which would be fine for now.

**Comment by ejucovy** [comment]
You can do this by adding "Site Assets" through the admin site: http://local.350.org/admin/assetmanager/siteasset/

With that you now can upload new images (and override existing images) for badges or anything else on the site.  You'll just need to look at the URL of the broken image that it's expecting to be able to find.  So for the energy-efficiency project, it's looking for an image at http://static.local.350.org/images/badges/energy-efficiency-action-badge-0-small.png -- so you should create a new Site Asset with "path" of `images/badges/energy-efficiency-action-badge-0-small.png` and upload the image file there.

**Comment by ejucovy** [comment]
In the long run a more user-friendly UI would probably be to let admins upload a badge image directly on the Add/Edit Project screen; the backend would ideally process that image and create all necessary sizes of the image and then upload them all to the static media server.

That will take some time to build, though, so let me know if the Site Asset solution I described in the previous comment is sufficient for the initial launch.

**Comment by abea** [comment]
Ah, thanks. I'll try that out later.

Alex Bea
(202) 525-6703 | http://350.org

On Fri, Jan 6, 2012 at 1:19 PM, ejucovy <
reply@reply.github.com
