### ISSUE TITLE
Event creation date format

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#165]
When I tried to create an event, I had to try several ways before I found you have to do it in the '2011-12-12' format. I added that into the Transifex item for "When," but it would be good if it wasn't as strict or we had a drop-down calendar folks could use.

**Comment by ejucovy** [comment]
> or we had a drop-down calendar folks could use.

There should be a drop-down calendar that appears when you click or tab into the "When" field.  Is that not showing up for you?

**Comment by abea** [comment]
No. And I keep having the problem with multiple tabs (like
theshttp://local.350.org/events/5/e)
appearing all together in one column of text, but just in Chrome. My
version is 16.0.912.75, the latest.

Alex Bea

On Wed, Jan 11, 2012 at 4:27 PM, ejucovy <
reply@reply.github.com

**Comment by ejucovy** [comment]
I still haven't been able to reproduce your Javascript errors in any browser, including the same version of Chrome.

Can you:
1. Press Ctrl+Shift+J to open the Developer Console in Chrome
2. Click on the "Console" tab on the right-hand side of the Console that pops up at the bottom of the screen
3. Visit http://local.350.org/events/5/ in the browser
4. See if any Javascript Errors appear in the Console window at the bottom of the screen?

Hopefully an error will pop up in there and help us get to the bottom of this.
