### ISSUE TITLE
Twitter auth doesn't seem to work

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#168]
Initially reported by another staff member, I tried linking my Twitter account twice and the oauth timed out both times.

**Comment by ejucovy** [comment]
Whoops -- looks like I neglected to update the Twitter account when we moved the site -- it was still pointing to groups.350.org instead of local.350.org.  I updated the settings and it's working for me now.

**Comment by abea** [comment]
Thanks, Ethan. Working now.

On Thu, Jan 26, 2012 at 5:20 PM, ejucovy <
reply@reply.github.com
