### ISSUE TITLE
Events not linking to groups

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#169]
A colleague and I both tried linking an event to our groups. I'm not seeing that link from the back end or on the respective group pages.

**Comment by ejucovy** [comment]
Hmm, it's working when I try it -- can you send me details of which event and which group you tried to link, and I'll see if I can reproduce the problem?

**Comment by abea** [comment]
For one, the event I created "More fun than a barrel full of coal powered
monkeys" was associated with 350 DC test originally and then I edited it to
be today. It isn't showing up on the group page, however.

http://local.350.org/350-dc/

Alex

On Thu, Jan 26, 2012 at 5:29 PM, ejucovy <
reply@reply.github.com

**Comment by ejucovy** [comment]
I suspect this is related to #170.  Can you try again and let me know if it still isn't working? 

If a (non-manager) member links an event to your group, it will result in a Group Association Request being created.  This needs to be moderated by a group manager in the "Requests and Notifications" tab.

**Comment by abea** [comment]
Works. Thanks, Ethan.

On Sat, Feb 4, 2012 at 6:54 PM, ejucovy <
reply@reply.github.com
