### ISSUE TITLE
Move Join group button

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#171]
With the reordering of tabs on individual groups (e.g., http://local.350.org/350-boulder/) the Join Group button is really buried. Please move that next to the Contact Group Leaders button in the top section.

**Comment by ejucovy** [comment]
Fixed in 63e8cbfc63a53645224aed797d229e08b5f6d4d0 -- also I moved the "Invite Friends" button to the same place.  (Only one or the other will ever show up, depending on whether you're a member of the group.)
