### ISSUE TITLE
Error when exporting users

### ISSUE THREAD

**Issue by abea** [350dotorg/localpower#175]
I tried to export four users from the Groups -> Users section (http://local.350.org/admin/groups/groupusers/) and got the error page:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, ejucovy@gmail.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
Apache/2.2.14 (Ubuntu) Server at local.350.org Port 80

**Comment by ejucovy** [comment]
This is now fixed.  Let me know if it comes up again with any other csv-exports from the admin site.  

(In short, CSV export will work for pages like /admin/groups/groupusers/ or /admin/auth/user/ which display their contents as columns in a formatted table, but it will not work for pages like /admin/groups/groupassociationrequest/ or /admin/group_links/externallink/ which don't use a structured table.  The fix I implemented for /groupusers/ was to change it to a structured table; I'd just apply that same fix to any other content types that you end up wanting to export.)
