### ISSUE TITLE
Server Error When Trying to Sign Petition

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#181]
http://cl.ly/2j0V0e0L2f3x1N3V0m1f

**Comment by ejucovy** [comment]
It looks like the Yahoo geocoder has suddenly stopped working, and is causing errors whenever the site tries to geocode anything.  I'm not sure why -- looking into it.

**Comment by ejucovy** [comment]
It appears Yahoo geocoder has suddenly started rejecting all requests that come in without a Yahoo API App ID.  I'm going to use my own API key for the sake of fixing this immediately, but we should circle back and transfer that key to 350.
