### ISSUE TITLE
Create Twitter and Facebook app IDs

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#19]
Need to create facebook applications for local, dev, and production environments. The main difference between these is the application URLS (127.0.0.1, dev.groups.350.org, groups.350.org). This will result in three application IDs and three secrets. Send keys and secrets to jonlesser. Add jonlesser@gmail.com, Jon W, and Ethan as developers on the facebook apps. 

Similar procedure for twitter. 

This is necessary for the Join/Login with facebook features to work.

Add keys to private bucket on S3 and add directly to the local_settings on the dev server.

**Comment by ejucovy** [comment]
I created a 350groups-dev Facebook application and put its app ID and secret in the AWS S3 private bucket, and on the staging server's local_settings directly.  

It looks like I can only add people on my FB friendslist as developers, so I just friended both of you.

I haven't yet created the FB apps for local and production environments (though the 350groups-dev app is currently pointing at groups.350.org) -- and haven't created any Twitter apps yet.

Based on cursory testing, the "Join us with Facebook" button is now working, and so is Facebook sharing (at least for projects completed, the only thing I've tested yet)

The Facebook Like button doesn't seem to be working yet, and the "Log in with Facebook" button doesn't seem to do anything.

Once I'm a little farther along with this ticket I'll file separate issues for those things.

**Comment by ejucovy** [comment]
What exactly is the functionality that requires the Twitter API keys?  The "Tweet" button seems to work without any API keys set -- though the "# of tweets" box above the button seems to still be displaying 0 after I've tweeted something.

I take it this has something to do with the (not yet working) "Link your Twitter Account" button on the edit-profile/account-settings -- but it's not clear to me what features will be enabled by linking my twitter account.  Automatic tweeting of actions I take, maybe?

**Comment by ejucovy** [comment]
> Automatic tweeting of actions I take, maybe?

Yup.  This only will happen if the user elects to share activity on Twitter, though (analogous to facebook share) -- which wasn't exposed in any form options until my recent commit 14fdb00266e996fc2a6ea3752689f1c0fef6eb77

Also it actually wasn't implemented -- I implemented the actual tweeting in 2893d30e05017ab54c1f22dd86e0dbf251bb02fc (and a few subsequent commits to fix typos)

Anyway, I also added a set of Twitter API keys to the staging site's local_settings and the private S3 bucket.

**Comment by ejucovy** [comment]
Some issues mentioned in comments here have been filed as: #75, #76

**Comment by ejucovy** [comment]
Since we have to create a whole slew of new settings for prod deployment including but not limited to these keys, and since I've filed separate issues now for peripheral things that have come up during this one, I'm going to close this as completed.
