### ISSUE TITLE
Profile edit pages needs to be fitted into a template.

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#26]
Profile edit page (/user/edit/<userid>) needs to be stuffed into a form page template. 

There are three sections to this page. Not sure if we should implement tabs or combine into one larger form. A similar problem exist for the group editing page.

**Comment by ejucovy** [comment]
Fixed primarily in f96e78c6 

Also in 3d085219 I corrected some typos which were causing the "Notifications" forms to be blank.

And in various commits around https://github.com/350org/localpower/compare/18c1010684...3d085219e7 I implemented jQuery UI tabs in a way that shouldn't mess up the site's layout or design -- so, for now at least, I'm going to keep the profile edit pages as separate forms in separate tabs.

**Comment by ejucovy** [comment]
See also 1ef3549 where I did much the same thing to the Group Edit page, which uses the same base template.
