### ISSUE TITLE
Google CSE for the site

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#27]
The search functionality is based on a Google Custom Search Engine. Create a new CSE that searches groups.350.org and add the ID to the templates. 

Should we just use 350's exiting CSE?
http://www.google.com/cse/home?cx=014706715754000189344:phzzho2nsim

Notes on CSEs:

The content of the site needs to be visible to Google for the indexing to happen. It can also take a day or two for new content to show up in the search results. 

The search also will always search against the live production site, even if the search originates on a dev or local instance.

**Comment by ejucovy** [comment]
I created a new CSE dedicated to groups.350.org and wired it up in 669439f
