### ISSUE TITLE
Project commitment widget

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#33]
Project commitment widget needs to work. 

Consider changing interaction from date pick on a calendar to time frame selected from a drop down (1 day, 1 week, 2 weeks, 3 weeks, 1 month, 3 months, 6 months, 1 year). 

Cancelling commitment isn't working either. 

"When do you think you'll complete this project?" at the bottom of project detail pages is from this.

**Comment by ejucovy** [comment]
The main issue was that the page's Javascript wasn't being included, because the `<script>` block that injected it was outside of the template's active `{% block %}`s and was therefore being ignored by the master template.

I fixed this, and also some tweaks so that it works right, in a044ccf
