### ISSUE TITLE
group settings page

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#46]
Editing group settings page needs to be cleaned up. Not sure if implementing tabs is better than have have three separate stand alone forms linked from the group detail page. 

After some work is done, maybe open more specific tickets.

**Comment by ejucovy** [comment]
Same approach (whatever that may be) needs to be taken for the profile-edit page.

Looking through the other edit forms, campaign-edit seems fine, and event-edit seems to not exist (it's an empty form)

**Comment by ejucovy** [comment]
Initial cleanup and tabbification done in 1ef3549e23e
