### ISSUE TITLE
Match group detail page with design comp

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#47]
There is a comp for group detail pages that needs to be attached to this ticket.

**Comment by ejucovy** [comment]
I don't have the comp yet, but there was some obvious low-hanging fruit in terms of the tabs now that I've worked out how to get jquery.ui tabs to play relatively nicely with the site's layout and design (about which see #26 and https://github.com/350org/localpower/compare/18c1010684...3d085219e7)

So, I wired up the tabs and touched up this page a bit in ba31d35cb7b -- giving it basically the same treatment that I gave the User Profile page in d5971352 (the two pages extend the same template)

The page now looks more or less workable, though the information design could probably use some work -- so I'm going to close this ticket -- but I'll revisit if you reopen it with the comp and/or other suggestions.

**Comment by ejucovy** [comment]
Meanwhile in 1ef3549 I tabbified the group edit page, though that has more to do with #26 implementation-wise.
