### ISSUE TITLE
Rewrite emails

### ISSUE THREAD

**Issue by jonlesser** [350dotorg/localpower#54]
The text of the Repower at Home emails is under a Creative Commons license, so it can be a starting point. But it should be updated for 350. For example, this is the email you receive after you create a new group:

Hi Jon,

I’m Shira, the Field Director for Repower at Home. My job is to bring the enthusiasm for saving energy that you find on repowerathome.com into the real world by working with leaders like you.

I see you recently created a community on repowerathome.com, Emeryville Green Alliance. Nice! Communities are a great way for a community to share ideas, compete with friends and work together to save energy.

As the community administrator, you can invite people to your community, moderate discussions and more by using the tools on your community’s page. Get started by inviting some friends to join your community. Try it out now.

Repower at Home communities often work to organize events in their communities, like energy meetings and challenges to recruit Trendsetters. The Repower at Home field team can tell you more about these opportunities. To get in touch, drop us a line at field@repowerathome.com. We’d love to hear your ideas for getting others energized about saving energy.

Happy energy savings,
Shira Miller
Field Director, Repower at Home

**Comment by ejucovy** [comment]
See also #94

**Comment by ejucovy** [comment]
Jon W rewrote these and I added them in cdad23c50db144924ef5a8cfa3fc6e6c81a5d332 and aefcf4d43da15f825b7625723d3f6e97d437e8c3
