### ISSUE TITLE
Email message when creating a "External Link Only" group should be distinct

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#61]
Currently the email message sent to the creator of an "External Link Only" group is identical to the one sent on creation of a normal group.  It should probably say different things instead, since a lot of the content of the standard group-creation email will likely be geared toward how to use the new group's features.

**Comment by jwarnow** [comment]
Is this something I should write? If so, should I submit it to you or
somewhere else?

**Comment by ejucovy** [comment]
Yeah -- I'll need to do a bit of work to integrate it into the site once it's written, so you can just send it to me or attach it to this ticket.  For reference, here's the current text of the email sent upon "normal" group creation:

```
<p>
Hi {{ recipient.first_name }},
</p>

<p>
 I’m Shira, the Field Director for Repower at Home. My job is to bring the enthusiasm for saving energy that you find on repowerathome.com into the real world by working with leaders like you.
</p>

<p>
I see you recently created a community on repowerathome.com, <a href=”http://{{ domain }}{{ content_object.get_absolute_url }}”>{{ content_object}}</a>. Nice! Communities are a great way for  a community  to share ideas, compete with friends and work together to save energy. 
</p>

<p>
As the community administrator, you can invite people to your community, moderate discussions and more by using the tools on your community’s page. <strong>Get started by inviting some friends to join your community</strong>. <a href=”http://{{ domain }}{{ content_object.get_absolute_url }}”>Try it out now</a>.
</p> 

<p>
Repower at Home communities often work to organize events in their communities, like <a href=”http://{{ domain }}/events/”>energy meetings</a> and challenges to recruit  <a href=”http://{{ domain }}/about-pledge/”>Trendsetters</a>. The Repower at Home field team can tell you more about these opportunities. To get in touch, drop us a line at <mailto:”field@repowerathome.com”>field@repowerathome.com</a>.  We’d love to hear your ideas for getting others energized about saving energy.
</p>

<p>
Happy energy savings,<br />
Shira Miller<br />
Field Director, Repower at Home 
</p>
```

As you can tell, obviously that email needs to be changed for 350.org's needs as well -- most if not all of the email messages do.  I'm going to collect all the messages (their contents, who they are sent to, and when they are sent) and send them to you separately for rewriting.

**Comment by jwarnow** [comment]
Cool -- I'll update this one as part of the big batch that you'll send
over...

**Comment by ejucovy** [comment]
I implemented the new message stream and a stub message in 0737d76 and manually loaded the new data fixture onto the staging server.  Since I'll include this in the batch of message contents to send you for editing, there's nothing more to be done for this message that's distinct from the work that all the messages will need; so I'll now close this ticket.
