### ISSUE TITLE
Flash messages when redirecting unauthorized requests to the login page

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#73]
Can we have a system message of sorts when you get redirected to a page because you're not logged in. Like, "Before you [register an event]/[start a group][whatever] you need to create an account. Don't worry -- it just takes 15 seconds!"

**Comment by ejucovy** [comment]
Implemented in 0a37910 with a generic message: "You need to create an account first. Don't worry -- it only takes 15 seconds!"  (This text will be available for editing in the Transifex interface next time I sync the translations.)

If we want customized messages for each instance ("Before you register an event" vs "Before you start a group" vs "Before you join a group" vs ... etc) it will take a lot longer -- using a generic message means I can change all instances with a single line of code, vs. catching each instance and writing a custom message for each one.

Of course, we can also take it case by case -- if there are particular actions that you think are sufficiently high-profile//common to merit their own custom versions of the message, I can do those while leaving the rest as a generic message.

**Comment by ejucovy** [comment]
There were also some additional cases that I missed in the first commit, which I caught in c5dbd90

**Comment by jwarnow** [comment]
I think a single message should be just fine.
