### ISSUE TITLE
Create email alias / distribution list to receive moderation/activity emails

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#74]
Analogous to #55, we should decide on an email address to receive the sorts of emails described in #63 -- "Somebody has created a new account" notifications as well as any other moderation-supporting emails we decide to wire up.

(See also #70, which was triggered because the email address currently wired up to receive these emails -- `newaccounts@repowerathome` -- no longer exists.)

**Comment by jwarnow** [comment]
Cool, just setup group-notifications@350.org

**Comment by ejucovy** [comment]
Fixed in the database and the data fixture, 1ad5a43

I think this should be moved to a `local_settings.py` variable, though, rather than living in the database.  Otherwise it'll be in multiple places in the database (per #63) and in fixtures, which feels wrong.
