### ISSUE TITLE
No mention of Twitter sharing on Ask To Share modal prompt

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#75]
The Ask To Share prompt only talks about Facebook, and doesn't give any opportunity to enable automatic sharing on Twitter.  The only way to enable Twitter sharing is on the account settings // profile-edit, where it's less likely to be noticed.

**Comment by jonlesser** [comment]
Also, automatic sharing over twitter isn't implemented. The only
functionality around twitter is linking your account. A while back we had a
module that let you post a tweet directly from our site, but it wasn't being
used and it didn't survive into the redesign.

I was imaging that some day the "ask to share" popup that appears after
completing or committing to a project would eventually have two checkboxes
(defaulted to checked) that would let you choose which linked accounts you
wanted to post to.

On Fri, Sep 9, 2011 at 5:46 AM, ejucovy <
reply@reply.github.com>wrote:

> The Ask To Share prompt only talks about Facebook, and doesn't give any
> opportunity to enable automatic sharing on Twitter.  The only way to enable
> Twitter sharing is on the account settings // profile-edit, where it's less
> likely to be noticed.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/350org/localpower/issues/75

## 

http://jonlesser.net
http://baltimorenode.org
http://www.bmorefiber.com

**Comment by ejucovy** [comment]
> Also, automatic sharing over twitter isn't implemented. The only functionality around twitter is linking your account. A while back we had a module that let you post a tweet directly from our site, but it wasn't being used and it didn't survive into the redesign.

I actually just wired up an implementation of this last night: https://github.com/350org/localpower/compare/2893d30e05017ab54c1f22dd86e0dbf251bb02fc...9eac474c44b6612fa249c6f9e801f3044e6784e0 -- in the course of digging around to figure out how things worked, I discovered it wasn't wired up, and it was simple enough to add that I just went ahead and did it.  So far in my casual testing it's been working well enough. So, I filed this current ticket to track the one remaining piece to be added to the UI for this to be meaningful.

**Comment by jonlesser** [comment]
Awesome!

And in general, amazing progress over the past few weeks. It's super
exciting to watch.

**Comment by ejucovy** [comment]
Implemented in 72419cb704d959ee1db87874335b8867f48307b0 and d884528ea68a31a9e93e246fa6973cac8b901407  For some reason the django form was misbehaving when i tried to use a MultipleChoiceField for social_network so I just implemented that by hand.

It remains a bit of a UX problem because the user has to know to also drop into his profile-edit page and "link" both his twitter and FB accounts before either will actually autoshare successfully, and we don't tell users this or prod them to do it (though we sort of do for FB with all the "Log in with Facebook" links -- but once you're logged in the prodding stops.)  But, I did change around the logic a bit so that the user can do these two things (link, and enable sharing) in any order for each social network.

**Comment by ejucovy** [comment]
Filed the UX problem as a lower-priority #105
