### ISSUE TITLE
Make flash messages stand out more visually

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#77]
Maybe with animations, and/or bigger text and different colors.

Currently the three types of messages --  "success", "info" and "error" -- are styled to be green, blue and orange respectively (since those seem to be the three main colors in the site's palette)

**Comment by jwarnow** [comment]
One other thing: can they go below the breadcrumb, so they are more visually connected to the content?  

And perhaps this can help? http://www.moretech.it/demo/plugins/jmNotify/

**Comment by ejucovy** [comment]
> And perhaps this can help? http://www.moretech.it/demo/plugins/jmNotify/

Wow, that looks great, thanks.

**Comment by ejucovy** [comment]
jmNotify actually is not so easy to integrate without rewriting a lot of the existing messages JS, so I ended up just making a couple of minor tweaks in the existing JS and CSS in 8219fcb which will hopefully do the trick.  The messages are each now in a slightly larger box (vertically padded) and their backgrounds flash to lightblue and back when the page loads, which will hopefully draw the eye without clashing too badly with any of the existing message colors...

Currently redeploying and resyncing with the S3 bucket so the change should be visible in 2-3 minutes.

Feel free to reopen this if you think these changes are not sufficient.

**Comment by jwarnow** [comment]
Hmm, these still are pretty subtle and blend in if you're not looking for them -- especially if there is also a modal share pop-up triggerred that grabs the users attentions (which we should probably disable, ya?).

Can we make the background orange, and place them below the breadcrumb?

**Comment by ejucovy** [comment]
> Can we make the background orange?

I'm already using orange for "Error" messages.  Which one(s) do you think should change -- blue or green (or both)?

I can switch "Error" messages to red maybe -- I'm guessing the blue ("info") are the hardest to notice.  So what if I try this set of colors:
- Success: green
- Info: orange
- Error: red

> and place them below the breadcrumb?

Yeah, let me figure this out -- it's just a bit complicated because not every page has a breadcrumb bar.

**Comment by jwarnow** [comment]
I'm thinking to make them more noticable, let's scrap blue and green, and
make success and info in orange, and error in red?

**Comment by ejucovy** [comment]
Ah OK, so merge success and info?  I'll give it a try.

**Comment by ejucovy** [comment]
I made the color swaps in 520f4a823b18c7320037e1114216d0960bb14d39 and moved the messages below the breadcrumbs (when both are present) in b253b94883dcb02dae9c866098d693c8591951fc

Deploying now, changes should be visible in a few minutes.

**Comment by jwarnow** [comment]
Beautiful -- one thing, can we disable the automated disappearing behavior?

**Comment by ejucovy** [comment]
No problem - done in 97f0f51
