### ISSUE TITLE
Use Facebook Comments instead of homegrown comments

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#79]
Jon W. said: "In some cases, I think maybe we can/should cut the "Discussions" tab, and instead use Facebook Comments boxes below the main event listing."

This seems to be the relevant widget: http://developers.facebook.com/docs/reference/plugins/comments/

The only necessary code is supposedly this:

```
<script>(function(d){
  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
  js = d.createElement('script'); js.id = id; js.async = true;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  d.getElementsByTagName('head')[0].appendChild(js);
}(document));</script>
<div class="fb-comments" data-href="example.com" data-num-posts="2" data-width="500"></div>
```

To attach separate comments on multiple pages I guess we'd need to set a different `data-href` for each one.

Note there are also moderation tools and additional settings.  To access these we'd need to add a META tag to the site to associate it with our app ID: `<meta property="fb:app_id" content="{YOUR_APPLICATION_ID}"/>`

**Comment by ejucovy** [comment]
Should we replace ALL of the "Discussions" tabs that use homegrown comment widgets? -- or just for the events.

Note that there are two styles of discussions implemented on the site: Group Discussions, which are more forum-like (multiple threads allowed, and an archive page) and which send emails to discussion participants and can be replied to by email; and all other discussions, which are light-weight mostly-single-threaded comment widgets that don't send email, can't be replied to by email, and have buttons for indicating whether a comment is a question/tip/idea/comment.

Should I swap in Facebook Comments for everything except for the (heavier-weight) Group Discussions?

**Comment by jonlesser** [comment]
I think the facebook comment plugin might be a good replacement everywhere
we currently use the threaded comments module (projects, events, and
campaigns). It would be clearer distinction between the functionality of
group discussions and more generic commenting.

On Fri, Sep 9, 2011 at 7:34 AM, ejucovy <
reply@reply.github.com>wrote:

> Jon W. said: "In some cases, I think maybe we can/should cut the
> "Discussions" tab, and instead use Facebook Comments boxes below the main
> event listing."
> 
> This seems to be the relevant widget:
> http://developers.facebook.com/docs/reference/plugins/comments/
> 
> The only necessary code is supposedly this:
> 
> ```
> <script>(function(d){
>  var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
>  js = d.createElement('script'); js.id = id; js.async = true;
>  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
>  d.getElementsByTagName('head')[0].appendChild(js);
> }(document));</script>
> <div class="fb-comments" data-href="example.com" data-num-posts="2"
> data-width="500"></div>
> ```
> 
> To attach separate comments on multiple pages I guess we'd need to set a
> different `data-href` for each one.
> 
> Note there are also moderation tools and additional settings.  To access
> these we'd need to add a META tag to the site to associate it with our app
> ID: `<meta property="fb:app_id" content="{YOUR_APPLICATION_ID}"/>`
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/350org/localpower/issues/79

## 

http://jonlesser.net
http://baltimorenode.org
http://www.bmorefiber.com

**Comment by jwarnow** [comment]
Agreed with Jon here, everywhere but group discussions.

**Comment by ejucovy** [comment]
Great - I swapped in FB comments sitewide.  4d26a5e

**Comment by ejucovy** [comment]
Oh also 0f0c98226aa062b was involved here -- the base template had been hardcoding an incorrect FB app id which I fixed to pull it from settings, as well as changing some HTML metadata tags per the FB lint checker's requests.

(Some additional metadata is requested, but not required, by the FB lint checker; we should add these: if done properly I think they would let comment updates in FB use the proper titles/images/descriptions for the object on our site that the comment is attached to.  Currently instead they all just talk about groups.350.org generically, though the links back are all correct.)

**Comment by ejucovy** [comment]
Just filed that last piece as a lower-priority #104.
