### ISSUE TITLE
"Create External Group" page is confusing

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#80]
> > > - The "create external group" page is a bit confusing. The title should be more like "Add my group to the map", plus "group address" field and "headquarters" field are also a bit baffling. Also, "upload group image" should be optional.
> > 
> > OK, I'll make the language changes.  As I suppose you can tell, I was a bit at a loss as to how to concisely describe these things in the interface.
> 
> Thanks! 
> 
> > Pretty sure "upload group image" is already optional?  Should we add an explicit "(optional)" label to clarify?
> 
> Yes, please do. 
> 
> > We can hide the "group address" field (which is actually the group's slug // URL on the groups.350.org site) and just generate it from the group name.
> 
> Yep, just generate it from the group name. 
> 
> > We do need to make room in the site's URL-space for the "internal homepage" of "external groups" in order for the group's creator to have somewhere to go to edit the group (change its external URL or description, delete it from the site, or promote it to a "full group") but this is sort of an implementation detail so we can hide it from the form -- does that sound good?
> 
> Sounds good. 
> 
> > The "headquarters" field is the group's location on the map, which I take it we want to require.  Should we change that field's label on the form to something more literal // less colloquial (like "Location")?  If so, should we make a corresponding change to the "Headquarters" field for "regular groups" too?
> 
> Yep, and I think we should add some help text too. Perhaps something likelike "Location" (include at least City, State, and Country)"

**Comment by ejucovy** [comment]
> The title should be more like "Add my group to the map", 

884e786

**Comment by ejucovy** [comment]
> > Pretty sure "upload group image" is already optional? Should we add an explicit "(optional)" label to clarify?
> 
> Yes, please do.

7023bc7

**Comment by ejucovy** [comment]
> > We can hide the "group address" field (which is actually the group's slug // URL on the groups.350.org site) and just generate it from the group name.
> 
> Yep, just generate it from the group name.

33cba01

**Comment by ejucovy** [comment]
> > The "headquarters" field is the group's location on the map, which I take it we want to require. Should we change that field's label on the form to something more literal // less colloquial (like "Location")? If so, should we make a corresponding change to the "Headquarters" field for "regular groups" too?
> 
> Yep, and I think we should add some help text too. Perhaps something likelike "Location" (include at least City, State, and Country)"

7b1f249

**Comment by jwarnow** [comment]
Re-opening this since I realized something: the external group feature was envisioned as a super streamlined, lightweight option for the people who have a group already and groan at the idea of having to join "yet another" thing. As such, it would be ideal if people could add their external groups to the map without creating an account. Thoughts?

**Comment by jwarnow** [comment]
Oh, and also: would it be possible to batch-import a bunch of existing external groups to the map that we know about?
