### ISSUE TITLE
Homepage should let people easily dive into a local group

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#81]
> > > Could we make the map the focus on the homepage?  I want people to be able to easily dive in to a local group. 
> > - Would the map replace any of the existing homepage content or supplement it (perhaps between the sliding panels at top and the "Featured Users/Groups" columns at bottom)? 
> 
> We could conceivable just make the the first sliding panel a JPG of the map -- probably easiest in the near term.  
> 
> > - Would the map contain all mappable content types -- events, users, groups?  If so, I think we'll need to find/build more map icons to differentiate the content types (which we should probably do anyway, even just for the individual content types' maps)
> 
> I was thinking just groups.

**Comment by jwarnow** [comment]
I think popping a static version of the groups map in panel/slider #1 is probably the easiest for now.

**Comment by ejucovy** [comment]
Implemented in 495c638 -- letting Google determine the zoom/center/bounds of the map based on the locations we tell it to mark.  The markers currently use no nearby-clustering logic, so it can end up looking pretty cluttered.  Which might be a good thing, if it makes things look busy and makes users want to click on it to look more closely.
