### ISSUE TITLE
Set up an email address for site emails to be sent from

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#82]
Currently I've set up the staging site to send emails from `greetings at coactivate dot org` which is an email address I control.  We should set up something at 350.org or at groups.350.org for emails to be sent from instead.

It needs to be a real address -- we need to be able to verify it with the PostmarkApp email service.

**Comment by jwarnow** [comment]
Use: messages@350.org

**Comment by ejucovy** [comment]
I set the new postmark API key in the local settings file, and we're now sending messages from `350 Groups <messages@350.org>` successfully.

**Comment by jwarnow** [comment]
Done! Screenshot attached. Hope it worked...
