### ISSUE TITLE
Customizing commitment page

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#85]
I can't find it in  Flat Pages, or in Transifex.

**Comment by ejucovy** [comment]
Do you mean the text at http://groups.350.org/commitments/ ?  I just added that to Transifex.  It's a little silly to be in Transifex and should probably be turned into a Flat Page instead, but for now this way is quicker.  I filed #90 for that nice-to-have reworking to a flatpage.

**Comment by jwarnow** [comment]
Yep, that's what I meant. I'll edit in Transifex for now.
