### ISSUE TITLE
Homepage doesn't lead logged-in users to their account/activity

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#91]
Now that we set up a single homepage (#71) for logged-in and anonymous users, rather than redirecting logged in users to their profile page, there's a sort of UX bug: visiting the site at groups.350.org doesn't give any easy entry points for a logged-in user to get to the meat of the site.  He has to scroll down and click on "Browse Groups" or "Browse Users" in order to get to a page that even has the navigation tabs.

Adding a map of groups (#81) will help, but we should also make it easier to get to the user's own profile/activity page.

The most obvious approach, I think, would be replacing the "CREATE AN ACCOUNT" sliding-panel with an alternate panel containing a "GO TO MY ACCOUNT" button if the user is logged in.

**Comment by jwarnow** [comment]
I like this solution...

**Comment by ejucovy** [comment]
Fixed in 32a600a and c9b7cda.  But, two notes:

1) I'm currently reusing the same image for both cases, which is a schematic overview of the site's features.  Dunno if that makes sense.

2) The text needs to be edited in Transifex and should be make quite a lot longer -- these panels were not designed for short text like "Welcome back to %(SITE_NAME)s" -- it should be at least a few lines long.

**Comment by jwarnow** [comment]
Cool, I added some more text for this one.

**Comment by ejucovy** [comment]
Hm, I don't see any new text showing up in the Transifex translations -- which message(s) did you add text for?  Can you double check that it got saved in Transifex?

**Comment by jwarnow** [comment]
Hm, it didn't. I just re-added it. I can't figure out how to link to a
specific translation in Transifex...too much ajax!

**Comment by jwarnow** [comment]
Hmm, maybe it didn't save. I'm getting the error: "Translation must start
with a newline (\n)"

thoughts?

**Comment by ejucovy** [comment]
Thanks, I see it there now when I search for "welcome back" ... yeah it's irritating that they don't give unique URLs for each message string.

**Comment by ejucovy** [comment]
> Hmm, maybe it didn't save. I'm getting the error: "Translation must start
> with a newline (\n)"
> 
> thoughts?

Looks like it worked fine anyway, it's now deployed and looking good.
