### ISSUE TITLE
Create Group Projects (and convert existing to "Projects" to "Solo Tasks")

### ISSUE THREAD

**Issue by jwarnow** [350dotorg/localpower#93]
In keeping with group-based movement-building goals, I'd like to orient the site and the user experience to encourage groups to take on projects. 

Here's what this would entail:
- Creating "Group Projects" (community-based, like "host a movie screening", "organize a climate potluck", "launch a local political pressure campaign") as separate from "Solo Tasks" (individually focused, like "change out your own lightbulbs", "write a letter to your representative"). Of course, there would be some language implications here: we should probably change the focus of the buttons on the projects to read "My group will do this" or "My group already did this."
- Group Badges (associated with group projects and displayed on a group page) as different than Solo Badges (associated with solo tasks, given displayed on a profile page). 
- Group Points (associated with group projects and displayed on a group page) as different than Solo Points (associated with solo tasks, given displayed on a profile page), with different potential rewards for each later on down the road. 

To be honest, I'd like to eventually integrate points/rewards in a strategic way, but ultimately am not convinced that the current integration of them is elegant enough or compelling enough to make them work -- not yet. I'm thinking to start, perhaps we should focus on badges (more for visual understanding of what a group is doing than for gamification purposes.) Later on down the road, I'd like to do more with points, but do it well, after doing some research. Just came across this video, which was helpful for me: http://youtu.be/7ZGCPap7GkY

Let me know if there's more info that would be useful here.

**Comment by ejucovy** [comment]
> we should probably change the focus of the buttons on the projects to read "My group will do this" or "My group already did this."

What would happen when these buttons are clicked?

Are they still time-oriented?  Would the user still associate a group commitment with a particular deadline?

And, would there be ramifications for the "Ask To Share" modal dialog // automatic Facebook/Twitter sharing that occurs afterwards?  Would the individual user still have a message posted/tweeted -- perhaps with different language, saying "My group [link here] just did so and so action [other link here]"?

**Comment by ejucovy** [comment]
> Group Points (associated with group projects and displayed on a group page) as different than Solo Points (associated with solo tasks, given displayed on a profile page)

Would solo points retain their existing behavior w.r.t groups -- which is that a group's points include a summation of all points accrued to any individual user who's a group member?  Or would groups just have their own completely independent points, which don't increment when individual user points increment?

Or are you thinking that we should hide points entirely again, and just kick this farther down the road?

**Comment by ejucovy** [comment]
Whew -- okay, initial implementation done in https://github.com/350org/localpower/compare/e7bfe835eb...5c98357e97

I haven't touched badges/points yet; just getting the models and forms in order was a pretty heavy lift.

I'll file a couple of separate issues for some loose ends that I haven't yet tackled.
