### ISSUE TITLE
"Reply by Email" message quoting considerations

### ISSUE THREAD

**Issue by ejucovy** [350dotorg/localpower#94]
When replying to a discussion by email, there will probably end up being a lot of quoted text ending up received by the server.  These are actually not so bad; here's a sample of the resulting output, based on just hitting "reply" in Gmail and not touching the quoted message part, as displayed on the site:

``
Here's a test reply (by email) to the test message.

On Thu, Sep 15, 2011 at 9:03 PM, Local Power so-and-so@example.comwrote:

> Hi Ethan Jucovy,
> Jon Warnow has posted a new discussion, Re: Welcome!, on your Long Island's
> community page.
> Re: Welcome!
> 
> Just a test message from Jon.
> 
> Click here to check it outhttp://groups.350.org/messaging/f78f1b396a765364807ced7d29bb8b8b38c150b4/
> 
> Thanks,
> The Repower at Home team
> 
> ``

Partly this isn't so bad because we are taking the plain-text version of the message if available, so a lot of the cruft from the original message (HTML and embedded CSS) will just be discarded.

That said, it might be worth considering approaches to improving this situation, because otherwise the discussion archives might end up getting very visually cluttered very quickly.  Three possibilities come to mind:

1) A redesign of the visual layout of the discussion archives might help give the page more space and make clutter issues less important.  (Not sure if this is true though.  But it feels a bit cramped to me; more so than the rest of the site even though it's the same layout.  Maybe somehow I have expectations that discussion archives should be roomier?)

2) I bet there exists some Javascript library that uses some heuristics to identify things that look like quoted text, and hides them under a Gmail-style "show/hide" button on the client side.

3) We could rewrite the message template that's sent out to discussion participants, so that it just includes the body of the message that was sent and a link to the discussion, without all of the "Hi so-and-so, Joe just posted a message on the site" stuff (and perhaps even without all the embedded CSS/HTML) -- this would make it feel less like a site notification and more like a mailing list.  (Which may be a pro or a con, depending on what you want out of it.)  It would also reduce the amount of text that's actually being quoted in a reply, and, in particular, reduce it to just what's directly relevant to the reply anyway, rather than boilerplate.

Seems like we can certainly defer any consideration of options 1 and 2.  But, option 3 might be worth doing while we are overhauling/rewriting all the emails anyway.

**Comment by jwarnow** [comment]
Yep, I like option #3 for this...

**Comment by ejucovy** [comment]
OK, I've stripped down the message to the essentials, and removed most of the HTML and CSS as well, so that there's less boilerplate/cruft quoted when replying to one of these by email.

**Comment by ejucovy** [comment]
7bde475063ca55c3cba666ac5eeee9a16cbf9e2c
